version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: obsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mydb:/var/lib/mysql
      - ./obsdb.sql:/docker-entrypoint-initdb.d/obsdb.sql
volumes:
  mydb:



